version: 2.1
jobs:
  build-android:
    docker:
      - image: kivy/buildozer:latest
    steps:
      - checkout
      - run:
          name: Build APK
          command: |
            if [ ! -f buildozer.spec ]; then
              # هنا نخبر الأداة بشكل صريح بالتخطي أثناء إنشاء الملف
              export FORCE_BUILDOZER_ALLOW_ROOT=1
              buildozer init
              sed -i 's/requirements = python3, kivy/requirements = python3, kivy, psutil/' buildozer.spec
              sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
            fi
            # تفعيل المتغير قبل أمر البناء الفعلي لمنع التحذير تماماً
            export FORCE_BUILDOZER_ALLOW_ROOT=1
            buildozer android debug
      - store_artifacts:
          path: bin/
          destination: apk-files
workflows:
  build:
    jobs:
      - build-android
      
